config/routes.rb
Plusdollar::Application.routes.draw do
  get "profiles/show"

  get "pages/index"
  get "pages/faq"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :pledges

  resource :profile, only: [:show, :update] do
    member do
      resource :payment, only: [:show, :create, :destroy]
    end
  end

  root :to => 'pages#index'

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  attr_accessible :amount, :title, :issue_url, :user_id, :user, :project_id

  validates :amount, presence: true

  scope :pricey, where('amount > ?', 10)
  scope :top_ten, order('amount desc').limit(10)

  scope :unresolved, where(closed: false)

  def user_name
    user.name if user
  end

  def cents
    (amount * 100).to_i
  end

  def charge_card(card)
    charge = Stripe::Charge.create(
      amount: cents,
      currency: "usd",
      card: card,
      description: "Pledge for #{title}"
    )
  end

  def github_issue
    uri = URI.parse(issue_url)
    user, project, _, id = uri.path.split('/').drop(1)
    Github.new.issues.get(user, project, id)
  end


  def load_title_from_github
    self.title = github_issue.title
    save
  end

  def load_state_from_github
    self.closed = github_issue.state == "closed"
    save
  end

  def resolve
    self.closed = true
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
   before_filter :authenticate_user!

  before_filter do
    @users = User.all
  end

  def pledges
    current_user.pledges
  end

  # GET /pledges
  # GET /pledges.json
  def index
    @pledges = pledges

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pledges }
    end
  end

  # GET /pledges/1
  # GET /pledges/1.json
  def show
    @pledge = Pledge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pledge }
    end
  end

  # GET /pledges/new
  # GET /pledges/new.json
  def new
     @pledge = pledges.build

    @users = User.all


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pledge }
    end
  end

  # GET /pledges/1/edit
  def edit
    @pledge = pledges.find(params[:id])
    @users = User.all
  end

  # POST /pledges
  # POST /pledges.json
  def create
    @pledge = pledges.new(params[:pledge])

    if @pledge.save
      @pledge.load_title_from_github
      redirect_to pledges_path, notice: 'Pledge was successfully created'
    else
      render action: "new"
    end
  end

  # PUT /pledges/1
  # PUT /pledges/1.json
  def update
    @pledge = pledges.find(params[:id])

      if @pledge.update_attributes(params[:pledge])
        redirect_to @pledge, notice: 'Pledge was successfully updated.'
      else
        render action: "edit"
      end
  end

  # DELETE /pledges/1
  # DELETE /pledges/1.json
  def destroy
    @pledge = pledges.find(params[:id])
    @pledge.destroy

    respond_to do |format|
      format.html { redirect_to pledges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/views/pledges/_form.html.erb
<%= form_for(@pledge, html: { class: 'form-horizontal' } ) do |f| %>
  <% if @pledge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pledge.errors.count, "error") %> prohibited this pledge from being saved:</h2>

      <ul>
      <% @pledge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="control-group">
  <%= f.label :issue_url,
              class: 'control-label' %>
  <div class="controls">
    <%= f.text_field :issue_url %>
  </div>
</div>

<div class="control-group">
  <%= f.label :amount,
              class: 'control-label' %>
  <div class="controls">
    <%= f.text_field :amount %>
  </div>
</div>
<div class="form-actions">
  <%= f.submit class: 'btn btn-primary' %>
</div>
<% end %>

app/views/pledges/_pledge.html.erb
  <tr>
    <td><%= pledge.issue_url %></td>
    <td><%= pledge.title %></td>
    <td><%= pledge.amount %></td>
    <td><%= pledge.user_name %></td>
    <td><%= link_to 'Show', pledge %></td>
    <td><%= link_to 'Edit', edit_pledge_path(pledge) %></td>
    <td><%= link_to 'Destroy', pledge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

app/views/pledges/edit.html.erb
<h1>Editing pledge</h1>

<%= render 'form' %>

app/views/pledges/index.html.erb
<%= render 'payment_alert' unless current_user.chargable? %>

<h1>Listing pledges</h1>

<table class="pledges">
  <tr>
    <th>Issue url</th>
    <th>Issue title</th>
    <th>Amount</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= render @pledges %>

</table>

<br />

<%= link_to 'New Pledge', new_pledge_path, id: 'new-pledge-link' %>

app/views/pledges/new.html.erb
<h1>New pledge</h1>

<%= render 'form' %>

app/views/pledges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Issue url:</b>
  <%= @pledge.issue_url %>
</p>

<p>
  <b>Issue title:</b>
  <%= @pledge.title %>
</p>

<p>
  <b>Amount:</b>
  <%= @pledge.amount %>
</p>

<p>
  <b>User:</b>
  <%= @pledge.user_name %>
</p>


<%= link_to 'Edit', edit_pledge_path(@pledge) %> |
<%= link_to 'Back', pledges_path %>