config/routes.rb
Plusdollar::Application.routes.draw do
  get "profiles/show"

  get "pages/index"
  get "pages/faq"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  resources :pledges

  resource :profile, only: [:show, :update] do
    member do
      resource :payment, only: [:show, :create, :destroy]
    end
  end

  root :to => 'pages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  layout :none_for_xhr
  def none_for_xhr
    'application' unless request.xhr?
  end

  def stash_referrer
    session[:stash] = request.referrer unless request.referrer == request.path
  end

  def redirect_back_or default
    redirect_to stashed_or(default)
  end

  def stashed_or default
    session[:stash] || default
  end
  helper_method :stashed_or

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar user
    image_tag Gravatar.new(user.email, size: 20).url, class: 'gravatar'
  end

  def stripe_button
    if Rails.env.test?
      submit_tag "Create Pledge"
    else
    javascript_include_tag "https://button.stripe.com/v1/button.js",
      class: "stripe-button",
      data: { key: Rails.configuration.stripe_public }
    end
  end
end

app/views/application/_flashes.html.erb
<% if alert %>
  <div class="alert alert-error">
    <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>

app/views/application/_nav.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "+:dollar:", root_path, class: "brand" %>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Pledges', pledges_path %></li>
          <li><%= link_to 'FAQ', pages_faq_path %></li>
        </ul>
        <% if user_signed_in? %>
          <%= render 'signed_in' %>
        <% else %>
          <%= render 'signed_out' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/application/_payment_alert.html.erb
<div class="alert alert-error">
  We don't have any payment info for you yet. You'll need to <%= link_to 'add payment info', payment_path %> before your pledges can get redeemed.
</div>

app/views/application/_signed_in.html.erb
<div class="navbar-form pull-right">
  <%= link_to profile_path, class: 'navbar-text' do %>
    <%= gravatar current_user %> <%= current_user.name %>
  <% end %>

  <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'logout btn' %>
</div>

app/views/application/_signed_out.html.erb
<%= form_for(User.new, url: session_path(:user), html: { class: 'navbar-form pull-right' }) do |f| %>
  <%= f.email_field :email, placeholder: "Email", class: "span2" %>
  <%= f.password_field :password, placeholder: "Password", class: "span2" %>
  <%= f.submit 'Sign in', class: 'btn btn-primary' %>
<% end %>